# Azure Pipelines YAML configuration file. Builds on multiple versions of Node.
#
# To learn more visit https://docs.microsoft.com/azure/devops/pipelines/get-started

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    Node8:
      node.version: '8.9.4'
    Node10:
      node.version: '10.12.0'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '$(node.version)'
  displayName: 'Install Node.js $(node.version)'

- script: |
    git fetch origin master:refs/remotes/origin/master -a

    git config user.name "Test name"
    git config user.email "test@users.noreply.github.com"

    node common/scripts/install-run-rush.js change -v
    node common/scripts/install-run-rush.js check
    node common/scripts/install-run-rush.js install
    node common/scripts/install-run-rush.js rebuild --verbose --production
  displayName: 'Build'
